// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tracker.Api.Data;

#nullable disable

namespace Tracker.Api.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260104094500_websession_url_and_device_reviewed")]
    partial class WebSessionUrlAndDeviceReviewed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Api.Data.AppSummaryRow", b =>
                {
                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Seconds")
                        .HasColumnType("bigint");

                    b.ToTable("AppSummaryRows");
                });

            modelBuilder.Entity("Tracker.Api.Data.DomainSummaryRow", b =>
                {
                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Seconds")
                        .HasColumnType("bigint");

                    b.ToTable("DomainSummaryRows");
                });

            modelBuilder.Entity("Tracker.Api.Data.IdleSecondsRow", b =>
                {
                    b.Property<long>("Seconds")
                        .HasColumnType("bigint");

                    b.ToTable("IdleSecondsRows");
                });

            modelBuilder.Entity("Tracker.Api.Models.AppSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindowTitle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "EndAt");

                    b.HasIndex("DeviceId", "StartAt");

                    b.ToTable("AppSessions");
                });

            modelBuilder.Entity("Tracker.Api.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Tracker.Api.Models.IdleSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "EndAt");

                    b.HasIndex("DeviceId", "StartAt");

                    b.ToTable("IdleSessions");
                });

            modelBuilder.Entity("Tracker.Api.Models.WebSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "EndAt");

                    b.HasIndex("DeviceId", "StartAt");

                    b.ToTable("WebSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
